# Generated by Django 5.2.8 on 2026-01-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
