# Generated by Django 5.2.8 on 2026-01-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image_post_tanggal_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
