# Generated by Django 5.2.8 on 2026-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_body_alter_post_category_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tanggal',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='post',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
